# Generated by Django 5.2.7 on 2025-10-26 08:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(default='', max_length=200)),
                ('nation', models.CharField(default='', max_length=200)),
                ('director', models.CharField(default='', max_length=200)),
                ('cast', models.CharField(default='', max_length=200)),
                ('story', models.TextField(default='')),
                ('runtime', models.IntegerField(default='')),
                ('m_date', models.IntegerField(default=django.utils.timezone.now)),
                ('genre1', models.CharField(default='', max_length=50)),
                ('genre2', models.CharField(default='', max_length=50)),
                ('anime', models.BooleanField(default=False)),
                ('m_age', models.CharField(default='', max_length=50)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('r_modify', models.BooleanField(default=False)),
            ],
        ),
    ]
