# Generated by Django 5.2.7 on 2025-10-26 14:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review_m_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='anime',
            field=models.BooleanField(default=False, verbose_name='애니'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.CharField(default='', max_length=200, verbose_name='출연진'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='등록일시'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=200, verbose_name='감독'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre1',
            field=models.CharField(default='', max_length=50, verbose_name='장르1'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre2',
            field=models.CharField(default='', max_length=50, verbose_name='장르2'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='m_age',
            field=models.CharField(default='', max_length=50, verbose_name='관람등급'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='m_date',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='개봉년도'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='m_name',
            field=models.CharField(default='', max_length=200, verbose_name='영화명'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='modify_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='수정일시'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='nation',
            field=models.CharField(default='', max_length=200, verbose_name='제작국가'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default='', verbose_name='상영시간'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='story',
            field=models.TextField(default='', verbose_name='줄거리'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='', verbose_name='리뷰 내용'),
        ),
        migrations.AlterField(
            model_name='review',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일시'),
        ),
        migrations.AlterField(
            model_name='review',
            name='m_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='영화명'),
        ),
        migrations.AlterField(
            model_name='review',
            name='r_modify',
            field=models.BooleanField(default=False, verbose_name='수정 여부'),
        ),
    ]
