# Generated by Django 5.2.7 on 2025-10-27 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_review_username_alter_movie_anime_alter_movie_cast_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="anime",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="nation",
        ),
    ]
