# Generated by Django 5.2.7 on 2025-10-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_remove_movie_anime_remove_movie_nation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre2",
            field=models.CharField(
                blank=True, default="", max_length=50, null=True, verbose_name="장르2"
            ),
        ),
    ]
