# Generated by Django 5.2.7 on 2025-10-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0005_alter_movie_genre2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre2",
            field=models.CharField(default="", max_length=50, verbose_name="장르2"),
        ),
    ]
