# Generated by Django 5.2.7 on 2025-10-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0006_alter_movie_genre2"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="mainphoto",
            field=models.ImageField(blank=True, null=True, upload_to="movies/"),
        ),
    ]
