# Generated by Django 5.2.7 on 2025-10-28 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0007_movie_mainphoto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="vote",
            field=models.ManyToManyField(
                related_name="vote_movie",
                to=settings.AUTH_USER_MODEL,
                verbose_name="추천",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="m_age",
            field=models.CharField(default="", max_length=50, verbose_name="이용등급"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="m_name",
            field=models.CharField(default="", max_length=200, verbose_name="영화제목"),
        ),
    ]
