# Generated by Django 5.2.7 on 2025-10-29 01:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0008_movie_vote_alter_movie_m_age_alter_movie_m_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="mainphoto",
            field=models.ImageField(
                blank=True, null=True, upload_to="movie/", verbose_name="이미지"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="vote",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="vote_movie",
                to=settings.AUTH_USER_MODEL,
                verbose_name="추천",
            ),
        ),
    ]
