# Generated by Django 5.2.7 on 2025-10-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0009_alter_movie_mainphoto_alter_movie_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="mainphoto",
            field=models.ImageField(
                blank=True, null=True, upload_to="m_img", verbose_name="이미지"
            ),
        ),
    ]
