# Generated by Django 5.2.7 on 2025-11-04 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0010_alter_movie_mainphoto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genre2",
        ),
        migrations.AlterField(
            model_name="movie",
            name="vote",
            field=models.ManyToManyField(
                blank=True,
                related_name="vote_movie",
                to=settings.AUTH_USER_MODEL,
                verbose_name="추천",
            ),
        ),
    ]
