# Generated by Django 5.2.7 on 2025-11-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0011_remove_movie_genre2_alter_movie_vote"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="vote",
        ),
        migrations.AddField(
            model_name="movie",
            name="vote",
            field=models.IntegerField(blank=True, default=0, verbose_name="추천수"),
        ),
    ]
